export type TabKey =
  | 'command-center'
  | 'data-sources'
  | 'distill-jobs'
  | 'distill-datasets'
  | 'distill-metrics'
  | 'production'
  | 'compare'
  | 'evaluations'
  | 'intelligence'
  | 'traces'
  | 'api-keys'
  | 'billing'
  | 'documentation'
  | 'community'
  | 'fine-tuning'
  | 'members'
  | 'organizations';
