export type TabKey =
  // Core
  | 'command-center'
  // Data
  | 'data-sources'
  // Build
  | 'distill-jobs'
  | 'distill-datasets'
  | 'distill-metrics'
  // Ship
  | 'production'
  // Validate
  | 'compare'
  // Evaluate
  | 'evaluations'
  // Intelligence
  | 'router-intelligence'
  // Monitor
  | 'observability'
  | 'traces'
  // Config
  | 'api-keys'
  | 'billing'
  | 'documentation'
  | 'community'
  | 'fine-tuning'
  | 'members'
  | 'organizations';
